// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IsSpZyV3UeIUTKugksrHNMEHwbLulfY',
    appId: '1:856002620487:web:cb65738db277c22c0e1562',
    messagingSenderId: '856002620487',
    projectId: 'meatshop-d9344',
    authDomain: 'meatshop-d9344.firebaseapp.com',
    storageBucket: 'meatshop-d9344.appspot.com',
    measurementId: 'G-TTP86GJF8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAV-0cd-_mD2Fr5CwmEU3F_zlUSq7Gls',
    appId: '1:856002620487:android:1afdcc33c63267e80e1562',
    messagingSenderId: '856002620487',
    projectId: 'meatshop-d9344',
    storageBucket: 'meatshop-d9344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVZiZ3RaC8htqlFu0dKlBuhPtMmfGzco',
    appId: '1:856002620487:ios:0ca137eacf834e2c0e1562',
    messagingSenderId: '856002620487',
    projectId: 'meatshop-d9344',
    storageBucket: 'meatshop-d9344.appspot.com',
    iosBundleId: 'com.example.meatShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVZiZ3RaC8htqlFu0dKlBuhPtMmfGzco',
    appId: '1:856002620487:ios:c33702244170497a0e1562',
    messagingSenderId: '856002620487',
    projectId: 'meatshop-d9344',
    storageBucket: 'meatshop-d9344.appspot.com',
    iosBundleId: 'com.example.meatShop.RunnerTests',
  );
}
